[module]
  [module.hugoVersion]
    extended = false
    min = "0.60.0"

baseURL = "/"
title = "FAOK, LLC Home"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"
#googleAnalytics = "G-XXXXXXXXXX"

[params]
fancyTitle = "FAOK" # title for frontpage, may include image
copyright = "FAOK, LLC"
description = "Information Technology and Software Development Services"
#startbuttonText = "Activate"
#startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#custom_sass = "bar.scss"
#images = ["path_to_social_image_for_link_previews.jpg"]

# [[params.menu.main]]
# url = '/'
# title = "Home"

[params.one]
enable = true
title = 'About'
body = '''
  FAOK, LLC has over 20 years of providing Information Technology and Software
  Development services in NYC.

  FAOK specializes in Cloud and IT procurement, vendor management, technical
  project management, solution architecture, and engineering management consultation.
'''

[params.two]
enable = true

[[params.two.section]]
img = "img/pic01.jpg"
img_alt = "blurry background: white/grey"
title = 'Information Technology Services'
body = 'Desktop Engineering to Device Management.'

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Software Development Services'
body = 'Backend to Frontend.'

[[params.two.section]]
img = "img/pic03.jpg"
title = 'Technical Project Management'
body = 'Kick-off to Delivery.'
